import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>VI Aerial Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <h1 className="m-auto">
          Welcome to <a href="https://nextjs.org">VI Aerial Solutions!</a>
        </h1>
        <img className="w-full" src="https://i0.wp.com/viaerialsolutions.com/wp-content/uploads/2020/04/DJI_0013-2-scaled.jpg?w=2340&ssl=1" />
      </main>

      <footer className={styles.footer}>Footer Section</footer>
    </div>
  );
}
